#%RAML 1.0
title: Digital Delta Eco Extensions - Measurements
version: 0.9.2
securitySchemes:
  basic:
    type: Basic Authentication
  oidc: ## OpenID Connect
    type: OAuth 2.0
baseUri: https://ddecotest.aquadesk.nl
mediaType: [ application/json ]
documentation:
  - title: About
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/About-Digital-Delta-Eco-API.md
  - title: Ecological Measurements
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Ecological-Measurements.md
  - title: Measurement level
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Measurement-level.md
  - title: Implementation topics
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Implementation-Topics.md
  - title: Contents of the Repository
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Contents-of-the-Repository.md
  - title: Change History
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Change-History-(Specification).md

uses: # Minimal types and definitions
  Measurements: Libraries/Measurements.raml
  Traits: Libraries/Traits.raml

/eco:
  /measurements:
    description:
      Retrieves a list of measurements.
    get:
      is: [ Traits.pageable, Traits.filterable, Traits.has403-AccessDeniedError, Traits.has500-ServerError ]
      securedBy: oidc
      responses:
        200:
          body:
            application/json:
              type: Measurements.MeasurementsListResponse
              example: !include AquaDesk Examples/Measurements.json

    /geojson:
      securedBy: oidc
      description:
        Retrieves a list of measurements as a GeoJSON FeatureCollection.
      get:
        is: [ Traits.pageable, Traits.filterable, Traits.has403-AccessDeniedError, Traits.has500-ServerError ]
        securedBy: oidc
        responses:
          200:
            body:
              application/json:
                type: object
                example: !include AquaDesk Examples/MeasurementsGeoJSON.json

    /filters:
      get:
        is: [ Traits.filterResponse]
