#%RAML 1.0
title: Digital Delta Eco Extensions - Measurements
version: 0.9.2
securitySchemes:
  basic:
    type: Basic Authentication
baseUri: https://ddecotest.aquadesk.nl
mediaType: [ application/json ]
documentation:
  - title: About
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/About-Digital-Delta-Eco-API.md
  - title: Ecological Measurements
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Ecological-Measurements.md
  - title: Measurement level
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Measurement-level.md
  - title: Implementation topics
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Implementation-Topics.md
  - title: Contents of the Repository
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Contents-of-the-Repository.md
  - title: Change History
    content: !include https://raw.githubusercontent.com/wiki/DigitaleDeltaOrg/dd-eco-api-specs/Change-History-(Specification).md

uses: # Minimal types and definitions
  Minimal: Libraries/Measurements.raml

/eco:
  /measurements:
    description:
      Retrieves a list of measurements.
    get:
      is: [ Minimal.pageable, Minimal.filterable ]
      responses:
        200:
          body:
            application/json:
              type: Minimal.MeasurementsListResponse
              example: !include AquaDesk Examples/Measurements.json

        400:
          body:
            application/json:
              type: Minimal.Problem
              example: !include AquaDesk Examples/Problem.json
    /geojson:
      description:
        Retrieves a list of measurements as a GeoJSON FeatureCollection.
      get:
        is: [ Minimal.pageable, Minimal.filterable ]
        responses:
          200:
            body:
              application/json:
                type: object
                example: !include AquaDesk Examples/MeasurementsGeoJSON.json

          400:
            body:
              application/json:
                type: Minimal.Problem
                example: !include AquaDesk Examples/Problem.json
    /filters:
      get:
        responses:
          200:
            body:
              application/json:
                type: Minimal.Filter[]
                example: !include AquaDesk Examples/Filter.json
